/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.nrg948.vision.visualizer;

import java.io.IOException;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application {
    private static Stage mainStage;

    public static Stage getMainStage() {
        return mainStage;
    }

    public void start(Stage mainStage) throws IOException {
        Parent root = FXMLLoader.load(getClass().getResource("App.fxml"));

        App.mainStage = mainStage;
        App.mainStage.setTitle("NRG948 Vision Targets Visualizer");
        App.mainStage.setScene(new Scene(root));
        App.mainStage.show();
    }

    public static void main(String[] args) {
        launch();
    }
}
